### ISSUE TITLE
Discord server for development discussion?

### ISSUE THREAD

**Issue by cfanoulis** [Geometrically/fabricate#13]
Hey there :wave:. Is there any Discord server/group for the development of Fabricate? 

Feel free to contact me on Discord as `enkiel#8897`

Thanks :)

**Comment by Aeledfyr** [comment]
There's a discord, that is now linked on the search page: https://discord.com/invite/JRMJpRX

**Comment by cfanoulis** [comment]
Great, thanks a lot

/close
